### ISSUE TITLE
Don't do that!

### ISSUE THREAD

**Issue by tonitch** [dxomg/vpsbot#3]
https://github.com/dxomg/vpsbot/blob/5bdbc14474aead5d2ed06f0a5277ad961f2d0ba0/lxcbot/main.py#L341

You should not remove that file!! this is really not the way as this file is really used by a lot of application.

Imo you should let the user handle the problem with known host by themself... they just have to do `ssh-keygen -R <ip>` and it's done....
but if you really want to, i'm pretty sure ssh have an option to bypass known_host check. should be something like StrictHostKeyChecking . so you do `ssh -o StrictHostKeyChecking=no`

**Comment by dxomg** [comment]
Done
