### ISSUE TITLE
Don't use global path, use local path instead

### ISSUE THREAD

**Issue by tonitch** [dxomg/vpsbot#5]
https://github.com/dxomg/vpsbot/blob/5bdbc14474aead5d2ed06f0a5277ad961f2d0ba0/lxcbot/main.py#L44

path like that sould be local and not global...
this could also be in config file. se by default to local then different installation would put their config file wherever they want

so by default I think you should do 

filelocation=./myfiles/

and use it on every path possible

**Comment by dxomg** [comment]
Done
