### ISSUE TITLE
Avoid hardcodding command in the code as much as possible

### ISSUE THREAD

**Issue by tonitch** [dxomg/vpsbot#6]
Hardcodding command in python and in any other language is really bad practice.. because you should not expect that the user use the system exactly as you do and because bad actor can use it at their advantage to bypass some security. do some ctf and you will find a lot of these exemple...

The best way is to find a lib that handle that for you (you could do syscall too but honestly, that's quite a leap in difficulty)
for instace you can use that https://github.com/lxc/python3-lxc You can check the code... there is some python interface to use and in the background it uses lxclib which handle lxc directly

same should exist for docker tho

**Comment by dxomg** [comment]
I've made sure to make the commands so that the user cannot bypass the security and execute bash commands

**Comment by tonitch** [comment]
> I've made sure to make the commands so that the user cannot bypass the security and execute bash commands

Bet...

**Comment by tonitch** [comment]
executing a command under linux is just executing a file which is in the $PATH var enviromenent.
As such. any command you type (excepts builtin) is just a file that can be altered and even hiden by modifying the PATH.
Even tho you made sure to serialize the user input and avoid any breach. there is always a way to mess with hardcoded commands.
So best way is to avoid using them if you can. in this case you can by just going trough the lib insteaf of the cl.
If there is no other way around, use full path for command (like /usr/bin/bash instead of bash) it will avoid going trough the PATH env and it would be more difficult (not impossible tho that's why you should avoid that) to alter the command file

But in the end, it's your project and you do as you want. I just think that people who want to use a product will always prefer the security and not choose those who think it's ok and won't think twice ^^

Edit: it's even more serious as you are running it as root... an attack like that on the system would give complete control of the system.
